### PR TITLE
allow domain names > HOST_NAME_MAX but < DOMAIN_NAME_MAX in dhcp client

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
What about in .network configs?

**Comment by mischief** [comment]
good catch.. PTAL @marineam

**Comment by marineam** [comment]
LGTM but commit message should be updated, something like:

```
network: allow domain names up to 255 characters

The maximum domain name size is larger than the maximum host name size. The smaller limit causes valid domains provided by DHCP to be silently ignored.
```

**Comment by mischief** [comment]
@marineam do you think it would be wise to add warnings as well when the domain is too long?

**Comment by marineam** [comment]
Well, it already does that for configs. Doing that for invalid DHCP data is not typical of networkd right now. not a bad thing to do but I wouldn't bother with it unless upstream wants to start being more verbose about invalid data in general.

**Pull request merged**
