### PR TITLE
units: use ProtectSystem=full

### PR DESCRIPTION
**Pull request by ajeddeloh**
This was added in c7fb922d6250543ba5462fa7a6ff03cc8f628e94 but causes
some bugs, so revert until they are resolved.

Bugs:
 - https://github.com/coreos/bugs/issues/2193
 - https://github.com/coreos/bugs/issues/2190
 - https://github.com/systemd/systemd/issues/7082

### CODE REVIEW

**Comment by bgilbert** [comment]
This is not quite a complete reversion of https://github.com/coreos/systemd/commit/c7fb922d6250543ba5462fa7a6ff03cc8f628e94.  Why were some pieces reverted and not others?

**Comment by ajeddeloh** [comment]
Commits after that one further changed the units, to the point where `git revert` cannot revert it. The `ReadWritePaths` have been replaced with RuntimeDirectory/other options in many places. I'm still testing this as well, to make sure it does what I expect; I opened this a little preemptively in retrospect.

**Comment by ajeddeloh** [comment]
Updated to be closer to pure reversion. Tested locally and passed all kola tests. Given that I can't reproduce the bug it fixes at all, that doesn't say a lot, but it matches the drop-in workaround that does work.

**Review by bgilbert — APPROVED** [review]
LGTM as an interim measure given https://github.com/systemd/systemd/issues/7082#issuecomment-347380436, assuming this fixes the reproducer in that comment.

**Pull request merged**
