### PR TITLE
Add networkd dbus

### PR DESCRIPTION
**Pull request by ajeddeloh**

### CODE REVIEW

**Comment by marineam** [comment]
Has this been sent upstream? What's the PR?

**Comment by ajeddeloh** [comment]
The first commit (fix dbus matchmac) has (and is merged). Second one I will send upstream later today.

**Comment by marineam** [comment]
Seems ok, but I'd like to see the upstream feedback on the new piece.

**Comment by ajeddeloh** [comment]
Just submitted to upstream here: https://github.com/systemd/systemd/pull/3528

**Comment by ajeddeloh** [comment]
Bump: switch RawOptions to PrivateOptions

**Comment by dm0-** [comment]
I'm going to close this since we're not on v229 anymore, and the upstream PRs were merged into v232.  We never upgraded to v232, but v233 appears to be nearing release.

**Pull request closed without merging**
