### PR TITLE
networkd: unlink link state file when freeing a link

### PR DESCRIPTION
**Pull request by mischief**
backporting patch for coreos/bugs#1081

### CODE REVIEW

**Comment by crawford** [comment]
Can you cherry-pick the actual patch? I have zero context for this change.

**Comment by mischief** [comment]
@crawford actual change doesn't apply. see coreos/bugs#1081.

**Comment by mpl** [comment]
Any news about that fix please? Do you have an estimate as to when we can see it land in the CoreOS stable image?

**Comment by marineam** [comment]
LGTM

**Pull request merged**
