### PR TITLE
v225 backports of some changes desirable for rkt

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by alban** [comment]
For the record, this PR contains 2 back ports requested on https://github.com/coreos/rkt/issues/1759:
- SELinux https://github.com/coreos/rkt/issues/2264 https://github.com/systemd/systemd/pull/2816
- rkt exit status https://github.com/coreos/rkt/issues/1460 https://github.com/systemd/systemd/pull/1318

**Comment by mischief** [comment]
lgtm

**Comment by alban** [comment]
Is this PR included in [CoreOS 899.11.0](https://coreos.com/releases/#899.11.0)?

**Comment by crawford** [comment]
No. It's going into the Alpha.

**Pull request merged**
