### PR TITLE
rules: whitelist xvd* devices

### PR DESCRIPTION
**Pull request by crawford**
Xen disks need to be whitelisted as well.

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by mischief** [comment]
lgtm

**Comment by crawford** [comment]
Verified that this works on AWS.

**Comment by marineam** [comment]
I wonder how big of a can of worms this is going to be, there are a lot of weird block devices out there. I bet cciss needs to be handled. Not sure what else.

**Comment by marineam** [comment]
Yeah, in fact commit 1aff20687f486857574fde0e5946a80b8ec212ba dropped some explicit references to cciss without any explanation. We will need to fix that as well.

**Pull request merged**
